apiVersion: v1
kind: Pod
metadata:
  name: db-test-automated
  namespace: edu-stanislav-hatylev
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    volumeMounts:
    - name: postgres-cert-volume
      mountPath: "/root/.postgresql/root.crt"
      subPath: "root.crt"                     #
      readOnly: true
  volumes:
  - name: postgres-cert-volume
    secret:
      secretName: postgres-ca-cert
      defaultMode: 0600