apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: edu-stanislav-hatylev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-site
  template:
    metadata:
      labels:
        app: django-site
    spec:
      containers:
      - name: django-container
        image: lekan29/django-app:176b632
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-db-urls
              key: url
        - name: SECRET_KEY
          value:  "django-insecure-my-very-secret-key-12345"
        - name: ALLOWED_HOSTS
          value: "edu-stanislav-hatylev.yc-sirius-dev.pelid.team"
        volumeMounts:
        - name: ssl-cert
          mountPath: "/root/.postgresql/root.crt"
          subPath: "root.crt"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: postgres-ca-cert
          defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: edu-stanislav-hatylev
spec:
  selector:
    app: django-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80