apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXRlc3Qta2V5LWZvci1taW5pa3ViZS0xMjM0NQ==
  DATABASE_URL: cG9zdGdyZXM6Ly9idXJnZXJ1c2VyOmJ1cmdlcnBhc3NAbXktcmVsZWFzZS1wb3N0Z3Jlc3FsOjU0MzIvc3RhcmJ1cmdlcg==
